server:
  port: 8080

spring:
  application:
    name: moodcode

  # MySQL Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moodcode?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root          # 본인 DB ID
    password: your_password # 본인 DB PW

  # JPA Setting
  jpa:
    hibernate:
      # 개발 초기에는 보통 update로 하고, 추후 빌드/테스트/배포시에는 validate로 변경할 것.
      ddl-auto: update # 개발 초기: update / 배포 시: validate
    properties:
      hibernate:
        format_sql: true # SQL 로그 예쁘게 출력
        show_sql: true
    defer-datasource-initialization: true

  # Redis Setting
  data:
    redis:
      host: localhost
      port: 6379
      # password: # 비밀번호 있는 경우에만 작성

  # OAuth2 소셜 로그인 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "구글_CLIENT_ID"
            client-secret: "구글_SECRET"
            scope: profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
          kakao:
            client-id: "카카오_REST_API_KEY"
            client-secret: "카카오_SECRET"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# JWT 설정
jwt:
  issuer: moodcode
  # 64바이트 이상 임의의 문자열 (운영 시 환경변수 처리 필수)
  client-secret: "MySuperSecretKeyForMoodcodeProjectMustBeLongerThan64BytesToUseHS512Algorithm!!"
  expiry-seconds: 1800 # 30분 (Access Token 짧게 유지)
  refresh-expiry-seconds: 1209600 # 14일 (Refresh Token)

logging:
  level:
    org.hibernate.SQL: debug